# Databricks notebook source
# MAGIC %md
# MAGIC # CLSA glaucoma: vessel, optic-disc, and foveal explainability
# MAGIC
# MAGIC This notebook extends notebook 08 **only within CLSA**. It intersects
# MAGIC participant-held-out RETFound glaucoma contribution maps with retinal
# MAGIC anatomy generated by the MIT-licensed Berens Lab
# MAGIC [`fundus_image_toolbox`](https://github.com/berenslab/fundus_image_toolbox).
# MAGIC
# MAGIC The package provides:
# MAGIC
# MAGIC - an FR-U-Net ensemble vessel **segmentation** trained on FIVES; and
# MAGIC - EfficientNet fovea and optic-disc center **localization** trained on
# MAGIC   ADAM, REFUGE, and IDRID.
# MAGIC
# MAGIC The optic-disc, peripapillary, and foveal outputs below are therefore
# MAGIC prespecified circular ROIs around localized centers—not pixel-level disc
# MAGIC or fovea segmentations. Every result preserves this distinction.
# MAGIC
# MAGIC Package source is pinned to commit
# MAGIC `d7757e28fbf639856b53cfe00019f605af8c1f17` for reproducibility.

# COMMAND ----------
# MAGIC %pip install -q "git+https://github.com/berenslab/fundus_image_toolbox.git@d7757e28fbf639856b53cfe00019f605af8c1f17" "huggingface_hub>=0.24"

# COMMAND ----------
from pathlib import Path
import hashlib
import importlib
import json
import math
import os
import sys

import joblib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from PIL import Image
from scipy import ndimage

# COMMAND ----------
dbutils.widgets.text(
    "repo_root",
    "/Workspace/Users/ad0038@pennmedicine.upenn.edu/CLSA/CLSA_retina",
)
dbutils.widgets.text(
    "age_glaucoma_output_root",
    "/Volumes/ophthalmology_analytics/dev_optic/clsa_dataset/derived/"
    "clsa_retinal_aging/Age_Glaucoma",
)
dbutils.widgets.text("notebook08_root", "")
dbutils.widgets.text("output_root", "")
dbutils.widgets.text("fit_cache_dir", "")
dbutils.widgets.text("segmentation_batch_size", "4")
dbutils.widgets.text("maximum_images", "0")
dbutils.widgets.dropdown("resume_segmentation", "true", ["true", "false"])
dbutils.widgets.text("vessel_threshold", "0.5")
dbutils.widgets.text("optic_disc_radius_scale", "0.20")
dbutils.widgets.text("fovea_radius_scale", "0.20")
dbutils.widgets.text("peripapillary_multiplier", "2.0")
dbutils.widgets.text("vessel_dilation_px", "2")
dbutils.widgets.text("permutations", "5000")
dbutils.widgets.text("bootstrap_repetitions", "2000")
dbutils.widgets.dropdown("run_targeted_occlusion", "false", ["false", "true"])
dbutils.widgets.text("occlusion_controls", "5")
dbutils.widgets.text("retfound_repo", "")
dbutils.widgets.text("checkpoint_path", "")
dbutils.widgets.dropdown("allow_repo_clone", "true", ["true", "false"])
dbutils.widgets.dropdown("allow_downloads", "true", ["true", "false"])
dbutils.widgets.text("hf_token", "", "Hugging Face token (temporary)")
dbutils.widgets.dropdown("device", "auto", ["auto", "cuda", "cpu"])

# COMMAND ----------
repo_root = Path(dbutils.widgets.get("repo_root").strip())
age_glaucoma_root = Path(
    dbutils.widgets.get("age_glaucoma_output_root").strip()
)


def configured_path(widget_name, default):
    value = dbutils.widgets.get(widget_name).strip()
    return Path(value) if value else Path(default)


notebook08_root = configured_path(
    "notebook08_root",
    age_glaucoma_root / "13_glaucoma_classifier_spatial_validation",
)
output_root = configured_path(
    "output_root",
    age_glaucoma_root / "14_clsa_anatomic_explainability",
)
fit_cache_dir = configured_path(
    "fit_cache_dir",
    age_glaucoma_root.parent
    / "model_checkpoints"
    / "fundus_image_toolbox",
)
segmentation_batch_size = int(dbutils.widgets.get("segmentation_batch_size"))
maximum_images = int(dbutils.widgets.get("maximum_images"))
resume_segmentation = dbutils.widgets.get("resume_segmentation") == "true"
vessel_threshold = float(dbutils.widgets.get("vessel_threshold"))
optic_disc_radius_scale = float(
    dbutils.widgets.get("optic_disc_radius_scale")
)
fovea_radius_scale = float(dbutils.widgets.get("fovea_radius_scale"))
peripapillary_multiplier = float(
    dbutils.widgets.get("peripapillary_multiplier")
)
vessel_dilation_px = int(dbutils.widgets.get("vessel_dilation_px"))
permutations = int(dbutils.widgets.get("permutations"))
bootstrap_repetitions = int(dbutils.widgets.get("bootstrap_repetitions"))
run_targeted_occlusion = (
    dbutils.widgets.get("run_targeted_occlusion") == "true"
)
occlusion_controls = int(dbutils.widgets.get("occlusion_controls"))
retfound_repo = dbutils.widgets.get("retfound_repo").strip() or None
checkpoint_path = dbutils.widgets.get("checkpoint_path").strip() or None
allow_repo_clone = dbutils.widgets.get("allow_repo_clone") == "true"
allow_downloads = dbutils.widgets.get("allow_downloads") == "true"
device_requested = dbutils.widgets.get("device")

if segmentation_batch_size < 1 or maximum_images < 0:
    raise ValueError("Batch size must be positive and maximum_images nonnegative")
if not 0 < vessel_threshold < 1:
    raise ValueError("vessel_threshold must lie in (0, 1)")
if not 0 < optic_disc_radius_scale <= 0.5:
    raise ValueError("optic_disc_radius_scale must lie in (0, 0.5]")
if not 0 < fovea_radius_scale <= 0.5:
    raise ValueError("fovea_radius_scale must lie in (0, 0.5]")
if peripapillary_multiplier <= 1:
    raise ValueError("peripapillary_multiplier must exceed 1")
if vessel_dilation_px < 0 or occlusion_controls < 1:
    raise ValueError("Dilation cannot be negative; controls must be positive")
if permutations < 500 or bootstrap_repetitions < 500:
    raise ValueError("Use at least 500 permutations and bootstrap repetitions")

module_root = repo_root / "src"
if str(module_root) not in sys.path:
    sys.path.insert(0, str(module_root))

import age_gap_extremes as _age_gap_extremes  # noqa: E402
import clsa_anatomic_explainability as _anatomic  # noqa: E402
import fundus_retfound_pipeline as _fundus  # noqa: E402
import glaucoma_classifier_spatial as _glaucoma  # noqa: E402

_age_gap_extremes = importlib.reload(_age_gap_extremes)
_anatomic = importlib.reload(_anatomic)
_fundus = importlib.reload(_fundus)
_glaucoma = importlib.reload(_glaucoma)

from age_gap_extremes import fundus_physiology_proxies  # noqa: E402
from clsa_anatomic_explainability import (  # noqa: E402
    attribution_region_metrics,
    build_anatomic_masks,
    participant_permutation_inference,
    sample_translated_control_masks,
)
from fundus_retfound_pipeline import (  # noqa: E402
    QualityConfig,
    RETFoundConfig,
    linear_head_score_from_array,
    load_retfound_model,
    prepare_model_input,
    preprocess_fundus,
    write_frame,
    write_json,
)
from glaucoma_classifier_spatial import (  # noqa: E402
    sample_equal_area_control_masks,
)

# COMMAND ----------
FIT_SOURCE_COMMIT = "d7757e28fbf639856b53cfe00019f605af8c1f17"
os.environ["FIT_CACHE_DIR"] = str(fit_cache_dir)
fit_cache_dir.mkdir(parents=True, exist_ok=True)
torch_cache_dir = fit_cache_dir / "torch"
torch_cache_dir.mkdir(parents=True, exist_ok=True)
os.environ["TORCH_HOME"] = str(torch_cache_dir)

import fundus_image_toolbox as fit  # noqa: E402

if device_requested == "auto":
    device = "cuda:0" if torch.cuda.is_available() else "cpu"
elif device_requested == "cuda":
    if not torch.cuda.is_available():
        raise RuntimeError("CUDA was requested but is unavailable")
    device = "cuda:0"
else:
    device = "cpu"
print("Fundus Image Toolbox version:", fit.__version__)
print("Pinned source commit:", FIT_SOURCE_COMMIT)
print("Anatomy device:", device)
print("Persistent FIT cache:", fit_cache_dir)

# COMMAND ----------
# MAGIC %md
# MAGIC ## 1. Load the completed CLSA-only notebook 08 explanations

# COMMAND ----------
attribution_manifest_path = (
    notebook08_root
    / "03_patch_attributions"
    / "glaucoma_attribution_manifest_private.parquet"
)
attribution_batch_root = notebook08_root / "03_patch_attributions" / "batches"
fold_heads_path = (
    notebook08_root
    / "01_participant_classifier"
    / "CLSA_glaucoma_oof_fold_heads.joblib"
)
required_paths = {
    "notebook 08 attribution manifest": attribution_manifest_path,
    "notebook 08 attribution batches": attribution_batch_root,
}
if run_targeted_occlusion:
    required_paths["notebook 08 fold heads"] = fold_heads_path
missing = [f"{name}: {path}" for name, path in required_paths.items() if not path.exists()]
if missing:
    raise FileNotFoundError("Required notebook 08 outputs are missing:\n- " + "\n- ".join(missing))

attribution_manifest = pd.read_parquet(attribution_manifest_path)
required_columns = {
    "image_key",
    "image_path",
    "participant_id",
    "source",
    "glaucoma_label",
    "fold",
    "classifier_logit_oof",
}
missing_columns = required_columns - set(attribution_manifest.columns)
if missing_columns:
    raise ValueError(
        "Notebook 08 attribution manifest is missing: "
        f"{sorted(missing_columns)}"
    )
clsa_images = attribution_manifest[
    attribution_manifest["source"].astype(str) == "CLSA"
].copy()
clsa_images["participant_id"] = clsa_images["participant_id"].astype(str)
clsa_images = clsa_images.drop_duplicates("image_path").sort_values(
    ["glaucoma_label", "participant_id", "image_path"], kind="stable"
)
if maximum_images:
    per_group = max(1, maximum_images // 2)
    stratified = [
        group.head(per_group)
        for _, group in clsa_images.groupby("glaucoma_label", sort=True)
    ]
    clsa_images = pd.concat(stratified, ignore_index=True).head(maximum_images)
if clsa_images.empty or set(clsa_images["glaucoma_label"].astype(int)) != {0, 1}:
    raise ValueError("CLSA anatomy analysis requires both glaucoma and healthy images")

map_paths = {}
for path in attribution_batch_root.rglob("*_exact_glaucoma_attribution.npz"):
    key = path.name.replace("_exact_glaucoma_attribution.npz", "")
    map_paths[key] = path
clsa_images["attribution_npz_path"] = clsa_images["image_key"].map(
    lambda key: str(map_paths.get(str(key), ""))
)
missing_maps = clsa_images["attribution_npz_path"].eq("")
if missing_maps.any():
    raise FileNotFoundError(
        f"{int(missing_maps.sum())} CLSA images lack saved exact attribution maps"
    )
print("CLSA images selected:", len(clsa_images))
print("CLSA participants:", clsa_images["participant_id"].nunique())
display(
    clsa_images.groupby("glaucoma_label").agg(
        images=("image_path", "count"),
        participants=("participant_id", "nunique"),
    )
)

# COMMAND ----------
# MAGIC %md
# MAGIC ## 2. Load pretrained vessel and landmark models
# MAGIC
# MAGIC Weights are downloaded by the toolbox on first use and retained under
# MAGIC the governed `fit_cache_dir`. No participant image is sent externally.

# COMMAND ----------
landmark_model, landmark_checkpoint = fit.load_fovea_od_model(
    device=device,
    cache_dir=str(fit_cache_dir),
)
vessel_ensemble = fit.load_segmentation_ensemble(
    device=device,
    cache_dir=str(fit_cache_dir),
)
print("Fovea/optic-disc checkpoint:", landmark_checkpoint)
print("Vessel ensemble models:", len(vessel_ensemble))


def sha256_file(path):
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


weight_paths = sorted(
    {
        path
        for pattern in ("*.pt", "*.pth", "*.ckpt")
        for path in fit_cache_dir.rglob(pattern)
        if path.is_file()
    }
)
weight_inventory = [
    {
        "filename": path.name,
        "relative_path": str(path.relative_to(fit_cache_dir)),
        "bytes": int(path.stat().st_size),
        "sha256": sha256_file(path),
    }
    for path in weight_paths
]
write_json(
    {"models": weight_inventory},
    output_root / "FIT_MODEL_WEIGHT_INVENTORY.json",
)
print("Cached anatomy model files inventoried:", len(weight_inventory))

# COMMAND ----------
# MAGIC %md
# MAGIC ## 3. Optional RETFound targeted occlusion
# MAGIC
# MAGIC The default run computes anatomy-specific attribution without replaying
# MAGIC RETFound. Set `run_targeted_occlusion=true` for the slower confirmatory
# MAGIC analysis. Start with `maximum_images=40` before scaling.

# COMMAND ----------
quality_config = QualityConfig(
    output_size=256,
    model_input_size=224,
    save_preprocessed=False,
)
fold_heads = None
retfound_model = None
resolved_checkpoint = None
if run_targeted_occlusion:
    fold_heads = joblib.load(fold_heads_path)
    retfound_config = RETFoundConfig(
        repo_path=retfound_repo,
        checkpoint_path=checkpoint_path,
        allow_downloads=allow_downloads,
        allow_repo_clone=allow_repo_clone,
        device="cuda" if device.startswith("cuda") else "cpu",
        batch_size=1,
    )
    temporary_hf_token = dbutils.widgets.get("hf_token").strip()
    if allow_downloads and not checkpoint_path and not temporary_hf_token:
        raise ValueError(
            "Enter the temporary hf_token or provide checkpoint_path for "
            "targeted occlusion."
        )
    if temporary_hf_token:
        os.environ["HF_TOKEN"] = temporary_hf_token
    try:
        retfound_model, retfound_device, resolved_repo, resolved_checkpoint = (
            load_retfound_model(retfound_config)
        )
    finally:
        os.environ.pop("HF_TOKEN", None)
        temporary_hf_token = ""
    print("RETFound occlusion device:", retfound_device)
    print("RETFound checkpoint:", resolved_checkpoint)

# COMMAND ----------
segmentation_root = output_root / "01_image_anatomy"
batch_root = segmentation_root / "batches"
mask_root = segmentation_root / "masks"
overlay_root = output_root / "02_overlays_private"
statistics_root = output_root / "03_statistics"
figure_root = output_root / "04_figures"
for path in (
    batch_root,
    mask_root,
    overlay_root,
    statistics_root,
    figure_root,
):
    path.mkdir(parents=True, exist_ok=True)


def resize_mask(mask, shape):
    nearest = getattr(Image.Resampling, "NEAREST", Image.NEAREST)
    image = Image.fromarray(np.asarray(mask, dtype=np.uint8) * 255)
    return np.asarray(image.resize((shape[1], shape[0]), nearest)) > 0


def stable_key(value):
    return hashlib.sha256(str(value).encode("utf-8")).hexdigest()[:20]


def sigmoid(value):
    return float(1.0 / (1.0 + np.exp(-np.clip(value, -40, 40))))


def occlusion_metrics(record, masks, retina):
    head = fold_heads[int(record["fold"])]
    model_array = prepare_model_input(record["image_path"], quality_config)
    shape = model_array.shape[:2]
    retina_model = resize_mask(retina, shape)

    def score(mask=None):
        altered = model_array.copy()
        if mask is not None:
            altered[mask] = 0.0
        return linear_head_score_from_array(
            retfound_model,
            head["coefficients"],
            head["intercept"],
            altered,
            retfound_device,
        )

    baseline = score()
    stored_logit = float(record["classifier_logit_oof"])
    replay_error = abs(baseline - stored_logit)
    if replay_error > 1e-3:
        raise RuntimeError(
            "CLSA targeted occlusion did not reproduce the held-out stored "
            f"logit within 0.001: difference={replay_error}"
        )
    output = {
        "occlusion_baseline_logit": baseline,
        "occlusion_baseline_probability": sigmoid(baseline),
        "occlusion_stored_logit_replay_error": replay_error,
    }
    localized = (
        masks["optic_disc_plus_peripapillary"] | masks["fovea_roi"]
    )
    excluded_controls = localized | masks["vessels"]
    for region_name in (
        "optic_disc_roi",
        "optic_disc_plus_peripapillary",
        "fovea_roi",
        "vessels_elsewhere",
    ):
        source_mask = masks[region_name]
        if region_name == "vessels_elsewhere" and vessel_dilation_px:
            source_mask = ndimage.binary_dilation(
                source_mask,
                iterations=vessel_dilation_px,
            ) & retina
        region = resize_mask(source_mask, shape) & retina_model
        if not region.any():
            continue
        region_drop = baseline - score(region)
        if region_name == "vessels_elsewhere":
            controls = sample_translated_control_masks(
                region,
                retina_model,
                resize_mask(excluded_controls, shape),
                n_masks=occlusion_controls,
                random_state=20260815 + int(record.name),
            )
        else:
            controls = sample_equal_area_control_masks(
                retina_model,
                resize_mask(excluded_controls, shape),
                target_area=int(region.sum()),
                n_masks=occlusion_controls,
                random_state=20260815 + int(record.name),
            )
        control_drops = np.asarray(
            [baseline - score(control) for control in controls],
            dtype=float,
        )
        output[f"{region_name}_occlusion_logit_drop"] = float(region_drop)
        output[f"{region_name}_control_drop_median"] = (
            float(np.median(control_drops)) if len(control_drops) else np.nan
        )
        output[f"{region_name}_specific_occlusion_drop"] = (
            float(region_drop - np.median(control_drops))
            if len(control_drops)
            else np.nan
        )
        output[f"{region_name}_n_control_masks"] = int(len(control_drops))
    return output


def save_overlay(rgb, attribution_grid, masks, label, output_path):
    resized = ndimage.zoom(
        np.asarray(attribution_grid, dtype=float),
        (
            rgb.shape[0] / attribution_grid.shape[0],
            rgb.shape[1] / attribution_grid.shape[1],
        ),
        order=1,
    )[: rgb.shape[0], : rgb.shape[1]]
    limit = max(float(np.quantile(np.abs(resized), 0.99)), 1e-8)
    fig, axes = plt.subplots(1, 4, figsize=(16, 4))
    axes[0].imshow(rgb)
    axes[0].set_title("Processed CLSA fundus")
    axes[1].imshow(rgb)
    axes[1].imshow(masks["vessels"], cmap="Reds", alpha=0.6)
    axes[1].set_title("FR-U-Net vessels")
    axes[2].imshow(resized, cmap="coolwarm", vmin=-limit, vmax=limit)
    axes[2].set_title("Exact glaucoma contribution")
    axes[3].imshow(rgb)
    axes[3].imshow(
        resized,
        cmap="coolwarm",
        alpha=0.45,
        vmin=-limit,
        vmax=limit,
    )
    for name, color in (
        ("optic_disc_roi", "cyan"),
        ("optic_disc_plus_peripapillary", "yellow"),
        ("fovea_roi", "lime"),
        ("vessels", "red"),
    ):
        axes[3].contour(
            masks[name], levels=[0.5], colors=[color], linewidths=0.8
        )
    axes[3].set_title(f"Anatomic overlay | label={int(label)}")
    for axis in axes:
        axis.axis("off")
    fig.tight_layout()
    fig.savefig(output_path, dpi=160)
    plt.close(fig)

# COMMAND ----------
# MAGIC %md
# MAGIC ## 4. Resumable CLSA anatomy inference

# COMMAND ----------
ordered = clsa_images.reset_index(drop=True)
batch_manifests = []
n_batches = math.ceil(len(ordered) / segmentation_batch_size)
for batch_index, start in enumerate(
    range(0, len(ordered), segmentation_batch_size), start=1
):
    stop = min(start + segmentation_batch_size, len(ordered))
    batch = ordered.iloc[start:stop].copy()
    batch_dir = batch_root / f"batch_{start:07d}_{stop:07d}"
    batch_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = batch_dir / "anatomic_explainability.parquet"
    if resume_segmentation and manifest_path.exists():
        existing = pd.read_parquet(manifest_path)
        required_resume = {
            "fit_source_commit",
            "anatomy_valid",
            "vessels_positive_enrichment",
            "optic_disc_roi_positive_enrichment",
            "fovea_roi_positive_enrichment",
        }
        occlusion_ready = (
            not run_targeted_occlusion
            or "optic_disc_roi_specific_occlusion_drop" in existing.columns
        )
        input_matches = (
            "image_key" in existing.columns
            and set(existing["image_key"].astype(str))
            == set(batch["image_key"].astype(str))
        )
        if (
            required_resume.issubset(existing.columns)
            and occlusion_ready
            and input_matches
        ):
            print(f"[anatomy {batch_index}/{n_batches}] resume {manifest_path}")
            batch_manifests.append(existing)
            continue
    print(f"[anatomy {batch_index}/{n_batches}] images {start:,}:{stop:,}")
    processed_images = []
    for record in batch.itertuples():
        processed = preprocess_fundus(record.image_path, quality_config)
        processed_images.append(np.asarray(processed.image.convert("RGB")))
    coordinates = landmark_model.predict(processed_images)
    coordinates = np.asarray(coordinates, dtype=float).reshape(-1, 4)
    vessel_predictions = fit.ensemble_predict_segmentation(
        vessel_ensemble,
        processed_images,
        device=device,
        size=(512, 512),
        threshold=vessel_threshold,
    )
    vessel_predictions = np.asarray(vessel_predictions, dtype=float)
    if vessel_predictions.ndim == 2:
        vessel_predictions = vessel_predictions[None, ...]
    rows = []
    for local_position, (_, record) in enumerate(batch.iterrows()):
        rgb = processed_images[local_position]
        vessel_mask = vessel_predictions[local_position]
        if vessel_mask.shape != rgb.shape[:2]:
            vessel_mask = np.asarray(
                Image.fromarray(vessel_mask.astype(np.float32)).resize(
                    (rgb.shape[1], rgb.shape[0]),
                    getattr(Image.Resampling, "BILINEAR", Image.BILINEAR),
                )
            )
        proxies = fundus_physiology_proxies(rgb)
        masks, anatomy_metadata = build_anatomic_masks(
            rgb.shape[:2],
            coordinates[local_position],
            vessel_mask,
            proxies["retina"],
            optic_disc_radius_scale=optic_disc_radius_scale,
            fovea_radius_scale=fovea_radius_scale,
            peripapillary_multiplier=peripapillary_multiplier,
        )
        with np.load(record["attribution_npz_path"]) as saved_map:
            attribution_grid = np.asarray(
                saved_map["variable_grid"], dtype=float
            )
        region_metrics = attribution_region_metrics(
            attribution_grid,
            proxies["retina"],
            masks,
        )
        key = stable_key(record["image_path"])
        mask_path = mask_root / f"{key}_anatomic_masks.npz"
        np.savez_compressed(
            mask_path,
            **{name: value.astype(np.uint8) for name, value in masks.items()},
        )
        overlay_path = overlay_root / f"{key}_anatomic_overlay.png"
        save_overlay(
            rgb,
            attribution_grid,
            masks,
            record["glaucoma_label"],
            overlay_path,
        )
        occlusion = (
            occlusion_metrics(record, masks, proxies["retina"])
            if run_targeted_occlusion and anatomy_metadata["anatomy_valid"]
            else {}
        )
        rows.append(
            {
                "image_key": str(record["image_key"]),
                "artifact_key": key,
                "image_path": record["image_path"],
                "participant_id": str(record["participant_id"]),
                "visit": record.get("visit"),
                "eye": record.get("eye"),
                "glaucoma_label": int(record["glaucoma_label"]),
                "fold": int(record["fold"]),
                "fit_source_commit": FIT_SOURCE_COMMIT,
                "fit_version": fit.__version__,
                "mask_path": str(mask_path),
                "overlay_path": str(overlay_path),
                **anatomy_metadata,
                **region_metrics,
                **occlusion,
            }
        )
    batch_manifest = pd.DataFrame(rows)
    write_frame(batch_manifest, manifest_path)
    batch_manifests.append(batch_manifest)
    print(
        f"[anatomy {batch_index}/{n_batches}] saved {len(batch_manifest)} rows; "
        f"valid={int(batch_manifest['anatomy_valid'].sum())}"
    )

image_anatomy = pd.concat(batch_manifests, ignore_index=True)
write_frame(
    image_anatomy,
    segmentation_root / "clsa_anatomic_explainability_private.parquet",
)
display(
    image_anatomy.groupby("glaucoma_label").agg(
        images=("image_path", "count"),
        participants=("participant_id", "nunique"),
        anatomy_valid_fraction=("anatomy_valid", "mean"),
        mean_vessel_fraction=("vessel_fraction_of_retina", "mean"),
    )
)

# COMMAND ----------
# MAGIC %md
# MAGIC ## 5. Participant-level CLSA glaucoma-versus-healthy inference

# COMMAND ----------
valid_images = image_anatomy[image_anatomy["anatomy_valid"]].copy()
if valid_images.empty:
    raise ValueError("No images passed anatomic localization/segmentation QC")
primary_metrics = [
    "optic_disc_roi_positive_enrichment",
    "peripapillary_annulus_positive_enrichment",
    "optic_disc_plus_peripapillary_positive_enrichment",
    "fovea_roi_positive_enrichment",
    "vessels_positive_enrichment",
    "vessels_elsewhere_positive_enrichment",
    "optic_disc_roi_absolute_enrichment",
    "peripapillary_annulus_absolute_enrichment",
    "fovea_roi_absolute_enrichment",
    "vessels_absolute_enrichment",
]
if run_targeted_occlusion:
    primary_metrics.extend(
        [
            "optic_disc_roi_specific_occlusion_drop",
            "optic_disc_plus_peripapillary_specific_occlusion_drop",
            "fovea_roi_specific_occlusion_drop",
            "vessels_elsewhere_specific_occlusion_drop",
        ]
    )
available_metrics = [
    column for column in primary_metrics if column in valid_images.columns
]
participant_anatomy = valid_images.groupby(
    ["participant_id", "glaucoma_label"], as_index=False
)[available_metrics].mean()
complete_metrics = [
    column
    for column in available_metrics
    if np.isfinite(
        pd.to_numeric(participant_anatomy[column], errors="coerce")
    ).all()
]
participant_anatomy = participant_anatomy[
    ["participant_id", "glaucoma_label", *complete_metrics]
]
if not complete_metrics:
    raise ValueError("No complete participant-level anatomic metrics remain")
if set(participant_anatomy["glaucoma_label"].astype(int)) != {0, 1}:
    raise ValueError("Valid anatomy participants do not include both CLSA groups")
group_counts = participant_anatomy.groupby("glaucoma_label")[
    "participant_id"
].nunique()
if group_counts.min() < 5:
    raise ValueError(
        "At least five valid participants per CLSA group are required for inference"
    )
write_frame(
    participant_anatomy,
    statistics_root / "participant_anatomic_metrics_private.parquet",
)
inference = participant_permutation_inference(
    participant_anatomy,
    complete_metrics,
    permutations=permutations,
    bootstrap_repetitions=bootstrap_repetitions,
)
write_frame(
    inference,
    statistics_root / "clsa_glaucoma_vs_healthy_anatomic_inference.csv",
)
display(inference.sort_values("permutation_p_max_t").round(5))

# COMMAND ----------
# MAGIC %md
# MAGIC ## 6. Publication figures and interpretation contract

# COMMAND ----------
positive_metrics = [
    "optic_disc_roi_positive_enrichment",
    "peripapillary_annulus_positive_enrichment",
    "optic_disc_plus_peripapillary_positive_enrichment",
    "fovea_roi_positive_enrichment",
    "vessels_elsewhere_positive_enrichment",
]
plot_metrics = [metric for metric in positive_metrics if metric in complete_metrics]
if plot_metrics:
    long_frame = participant_anatomy.melt(
        id_vars=["participant_id", "glaucoma_label"],
        value_vars=plot_metrics,
        var_name="region_metric",
        value_name="positive_attribution_enrichment",
    )
    fig, axis = plt.subplots(figsize=(12, 6))
    groups = []
    labels = []
    for metric in plot_metrics:
        for label in (0, 1):
            groups.append(
                long_frame[
                    (long_frame["region_metric"] == metric)
                    & (long_frame["glaucoma_label"] == label)
                ]["positive_attribution_enrichment"].to_numpy()
            )
            labels.append(f"{metric.replace('_positive_enrichment', '')}\n{['healthy', 'glaucoma'][label]}")
    axis.boxplot(groups, labels=labels, showfliers=False)
    axis.axhline(1.0, color="black", linestyle="--", linewidth=1)
    axis.set_ylabel("Positive attribution enrichment over retinal area")
    axis.set_title("CLSA held-out glaucoma-map evidence by retinal anatomy")
    axis.tick_params(axis="x", rotation=35)
    fig.tight_layout()
    fig.savefig(
        figure_root / "clsa_anatomic_attribution_enrichment.png",
        dpi=200,
    )
    display(fig)
    plt.close(fig)

valid_fraction = float(image_anatomy["anatomy_valid"].mean())
significant_regions = inference.loc[
    inference["permutation_p_max_t"] < 0.05,
    "metric",
].tolist()
summary = {
    "analysis": "CLSA_glaucoma_vs_healthy_anatomic_explainability",
    "scope": "CLSA only; Zeiss excluded",
    "fundus_image_toolbox": {
        "source_commit": FIT_SOURCE_COMMIT,
        "installed_version": fit.__version__,
        "weight_inventory": str(
            output_root / "FIT_MODEL_WEIGHT_INVENTORY.json"
        ),
        "license": "MIT",
        "vessel_model": "FR-U-Net ensemble trained on FIVES",
        "landmark_model": (
            "multitask EfficientNet trained on ADAM, REFUGE, and IDRID"
        ),
    },
    "anatomy_definitions": {
        "vasculature": "pixel segmentation from the FR-U-Net ensemble",
        "optic_disc": "circular ROI around localized center; not segmentation",
        "peripapillary": "annulus around the localized optic-disc ROI",
        "fovea": "circular ROI around localized center; not segmentation",
    },
    "n_images": int(len(image_anatomy)),
    "n_participants": int(image_anatomy["participant_id"].nunique()),
    "anatomy_valid_fraction": valid_fraction,
    "targeted_occlusion_ran": run_targeted_occlusion,
    "max_t_significant_metrics": significant_regions,
    "claim_gate": {
        "participant_level_inference": True,
        "held_out_classifier_maps": True,
        "anatomy_valid_fraction_at_least_0_90": valid_fraction >= 0.90,
        "multiplicity_control": "max-|T| permutation across region metrics",
        "localized_rois_not_mislabeled_as_segmentations": True,
    },
    "limitations": [
        "CLSA glaucoma status is released physician-diagnosed self-report.",
        "The landmark model supplies centers, not optic-disc/fovea boundaries.",
        "External anatomy models require CLSA-specific visual validation.",
        "Vessel masks do not distinguish arteries from veins.",
        "Attribution enrichment is associative; targeted occlusion is stronger but still model-based.",
    ],
    "outputs": {
        "image_anatomy": str(
            segmentation_root / "clsa_anatomic_explainability_private.parquet"
        ),
        "participant_metrics": str(
            statistics_root / "participant_anatomic_metrics_private.parquet"
        ),
        "inference": str(
            statistics_root / "clsa_glaucoma_vs_healthy_anatomic_inference.csv"
        ),
    },
}
write_json(summary, output_root / "CLSA_ANATOMIC_EXPLAINABILITY_SUMMARY.json")
print(json.dumps(summary, indent=2, default=str))

# COMMAND ----------
os.environ.pop("HF_TOKEN", None)
try:
    dbutils.widgets.remove("hf_token")
except Exception:
    pass
print("Notebook 09 complete; temporary Hugging Face token widget removed")
